config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'movielist', to: 'movielist#index'
  # namespace 'admin' do
  #   get 'movies', to: 'movies#index'
  # end

  root  'movies#index'

  resources :movies do
    resources :schedules do
      resources :sheets, only: :index, shallow: true 
      resources :reservations
    end
    get :setup_resevation
  end

  # /movies/:movie_id/schedules/:schedule_id/sheets 座席予約
  # /movies/:movie_id/schedules/:schedule_id/reservations/new 座席予約フォーム
  # resource :movies do
  #   collection do
  #     get :movies/:movie_id/schedules/:schedule_id/sheets 
  #     get :movies/:movie_id/schedules/:schedule_id/reservations/new
  #   end
  # end
  resources :sheets, only: :index
  resources :schedules

  # get 'admin/movies', to: 'admin/movies#index'
  # get 'admin/movies/new', to: 'admin/movies#new'
  # post 'admin/movies', to: 'admin/movies#create'
  # get 'admin/movies/:id/edit', to: 'admin/movies#edit'
  # delete 'admin/movies/:id', to: 'admin/movies#destroy'
  # put 'admin/movies/:id', to: 'admin/movies#update'

  namespace :admin do
    resources :movies do
      resources :schedules, shallow: true 
    end
    resources :reservations
  end
# shallow: true idがくどい時
# GET等は極力使わない
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :schedules, dependent: :destroy  
  validates :name, presence: true, length: { maximum: 160 }, uniqueness: true
  validates :year, length: { maximum: 45 }, numericality: { only_integer: true }
  validates :image_url, length: { maximum: 1000 }

  def self.search(search, is_showing) 
    if search 
      if is_showing == "0"
        Movie.where(['name LIKE ? OR description LIKE ?', "%#{search}%", "%#{search}%"]).where(is_showing: "0")
      elsif is_showing == "1"
        Movie.where(['name LIKE ? OR description LIKE ?', "%#{search}%", "%#{search}%"]).where(is_showing: "1")
      else
        Movie.where(['name LIKE ? OR description LIKE ?', "%#{search}%", "%#{search}%"])
      end
    else
      Movie.all
    end
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, { presence: true, format: { with: VALID_EMAIL_REGEX } }
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :movie

  validates :start_time, presence: true
  validates :end_time, presence: true

end

app/models/sheet.rb
class Sheet < ApplicationRecord
end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < ApplicationController

  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
    @schedule = Schedule.find_by(movie_id: @movie.id)
  end

  def new
    @movie = Movie.new(flash[:movie])
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    movie = Movie.find(params[:id])

    if movie.update(movies_params)
      redirect_to admin_movies_path
    else
      redirect_to edit_admin_movie_path, flash: {
        movie: movie,
        error_messages: movie.errors.full_messages
      }
    end
  end
  
  def create
    movie = Movie.new(movies_params)
    if movie.save
      redirect_to admin_movies_path
    else
      redirect_to new_admin_movie_path, flash: {
        movie: movie,
        error_messages: movie.errors.full_messages
      }
    end
  end

  def destroy
    movie = Movie.find(params[:id])
    movie.destroy
    redirect_to admin_movies_path ,flash: { notice: "削除されました" }
  end

  private
  def movies_params
    params.require(:movie).permit(:name, :year, :description, :image_url, :is_showing)
  end
  
end

app/controllers/admin/reservations_controller.rb
class Admin::ReservationsController < ApplicationController
  def index
    @reservations = Reservation.all
    # @reservations.each do |item|
    #   p '---------'
    #   p Movie.find(item.movie_id)
    #   p '---------'
      
    # end
    @movies = Movie.all
  end
  
  def new
    
  end

  def edit
    @reservations = Reservation.find(params[:id])
  end
  
  def destroy
    reservations = Reservation.find(params[:id])
    reservations.destroy
    redirect_to admin_reservations_path ,flash: { notice: "削除されました" }
  end
  
end

app/controllers/admin/schedules_controller.rb
class Admin::SchedulesController < ApplicationController

  def index
    @schedules = Schedule.includes(:movie).where(movie_id: params[:movie_id])
    @schedule = Schedule.find_by(movie_id: params[:movie_id])
    @schedule_name = Movie.find(params[:movie_id]).name
    # 映画詳細と紐づくスケジュールを表示
  end

  def show
    @schedule = Schedule.find_by(movie_id: params[:id])
  end
  
  def new
    @schedule = Schedule.new(flash[:schedule])
  end

  def create
    movie = Movie.find(params[:movie_id])
    schedule = movie.schedules.new(schedule_params)
    # schedule.movie = movie
    # schedule.movie_id = movie.id
    # movie.schedules.new(schedule_params)アソシエーション
    if schedule.save
      redirect_to admin_movie_schedules_path(movie_id: schedule.movie_id)
    else
      redirect_to new_admin_movie_schedule_path(movie_id: params[:movie_id]), flash: {
        schedule: schedule,
        error_messages: schedule.errors.full_messages
      }
    end
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    schedule = Schedule.find(params[:id])

    if schedule.update(schedule_params)
      redirect_to admin_movie_schedules_path(movie_id: schedule.movie_id)
    else
      redirect_to edit_admin_schedule_path, flash: {
        schedule: schedule,
        error_messages: schedule.errors.full_messages
      }
    end
  end

  def destroy
    schedule = Schedule.find(params[:id])
    schedule.destroy
    redirect_to admin_movie_schedules_path(movie_id: params[:movie_id]) ,flash: { notice: "削除されました" }
  end

  private

  def schedule_params
    params.require(:schedule).permit(:start_time, :end_time)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.search(params[:search], params[:is_showing])
  end

  def show
    @movie = Movie.find(params[:id])
    @schedule =  Schedule.where(movie_id: @movie.id)
    start_time = @schedule.map { |i| i.start_time }
    end_time = @schedule.map { |i| i.end_time }
    @schedule_hash = { start_time: start_time, end_time: end_time }

    time = Schedule.where(movie_id: params[:id]).pluck(:start_time)
    make_time = time.map { |i| i.strftime("%H:%M") }

    @time_arr = []
    # 二次元配列作成
    time.each do |_|
      @time_arr.push([])
    end
    # f.selectの値を調整する
    time.each.with_index do |item, i|
      @time_arr[i].push(make_time[i], item)
    end

  end

  def setup_resevation
    movie_id = params[:movie_id]
    start_time = params[:start_time]
    schedule_id = Schedule.find_by(start_time: start_time)
    
    redirect_to movie_schedule_sheets_path(movie_id: movie_id, schedule_id: schedule_id, start_time: start_time)
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def index
  end
  
  def new
    @reservation = Reservation.new
  end
  
  def create
    reservation = Reservation.new(reservation_params)
    is_reserved = Reservation.exists?(date: params[:date], sheet_id: params[:sheet_id])

    if is_reserved
      flash[:error] = "その座席はすでに予約済みです"
      redirect_to movie_schedule_sheets_path(movie_id: params[:movie_id], schedule_id: params[:schedule_id], sheet_id: params[:sheet_id], start_time: params[:date])
      return
    end
    
    if reservation.save
      flash[:notice] = "予約が完了しました"
      redirect_to movie_path(params[:movie_id])
    end
  end

  private

  def reservation_params

    # movie_idがnilになる
    params.permit(:email, :name, :date, :sheet_id, :schedule_id, :movie_id)
  end
end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
  def index
    @sheets = Sheet.all
    @reserved_sheet_ids = Reservation.where(date: params[:start_time]).pluck(:sheet_id)

    # is_reserved = Reservation.find_by(date: params[:start_time])[:sheet_id].present?
    # is_reserved = params[:sheet_id].present?
    # @reserved_sheet_id = Reservation.find_by(date: params[:start_time])[:sheet_id]
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/admin/movies/_form.html.erb
<div class="container mt-4">
  <%= render "layouts/error_messages" %>
  <div class="d-flex align-items-center justify-content-center mt-2">
    <%= f.label :name, "タイトル", class: "col-sm-2 col-form-label" %>
    <div class="col-md-4">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="d-flex align-items-center justify-content-center mt-2">
    <%= f.label :year, "公開年", class: "col-sm-2 col-form-label" %>
    <div class="col-md-4">
      <%= f.text_field :year, class: "form-control" %>
    </div>
  </div>
  <div class="d-flex align-items-center justify-content-center mt-2">
    <%= f.label :description, "概要", class: "col-sm-2 col-form-label" %>
    <div class="col-md-4">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>
  <div class="d-flex align-items-center justify-content-center mt-2">
    <%= f.label :is_showing, "上映中", class: "col-sm-2 col-form-label" %>
    <div class="col-md-4">
      <%= f.check_box :is_showing, :as => :boolean, checked:false %>
    </div>
  </div>
</div>

app/views/admin/movies/edit.html.erb
<div class="container ">
  <%= form_for @movie, url: admin_movie_path(@movie) do |f| %>
    <%= render :partial => 'form', :locals => {:f => f} %>
    <div class="d-flex justify-content-center mt-2">
      <%= f.submit t('update'), class: 'btn btn-outline-dark col-md-2' %>
      <%= link_to '戻る', admin_movies_path, class: 'btn btn-outline-dark col-md-2 ml-2' %>
    </div>
  <% end %>
</div>

app/views/admin/movies/index.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center">
    <h1 >movie</h1>
    <% if flash[:notice] %>
      <div class="alert alert-danger"><%= flash[:notice] %></div>
    <% end %>
    <%= link_to "新規登録", new_admin_movie_path, class: 'btn btn-primary' %>
  </div>
  <div class="mt-2">
    <table class="table">
      <thead>
        <th>ID</th>
        <th>タイトル</th>
        <th>公開年</th>
        <th>概要</th>
        <th>上映中</th>
        <th>登録日時</th>
        <th>更新日時</th>
        <th></th>
        <th></th>
        <th></th>
      </thead>
      <tbody>
        <% @movies.each do |movie| %>
          <tr class="mt-1">
            <td><%= movie.id %></td>
            <td><%= movie.name %></td>
            <td><%= movie.year %></td>
            <td><%= simple_format(movie.description) %></td>
            <td>
              <% if movie.is_showing %>
                上映中
              <% else %>
                上映予定
              <% end %>
            </td>
            <td><%= l movie.created_at %></td>
            <td><%= l movie.updated_at %></td>
            <td><%= link_to 'スケジュール', admin_movie_schedules_path(movie), class: 'btn btn-outline-dark' %></td>
            <td><%= link_to '修正', edit_admin_movie_path(movie), class: 'btn btn-outline-dark' %></td>
            <td><%= link_to "削除", admin_movie_path(movie.id), class: 'btn btn-outline-danger', method: :delete, data: { confirm: "削除しますか？" } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/movies/new.html.erb
<div class="container">
  <%= form_for @movie, url: admin_movies_path do |f| %>
    <%= render :partial => 'form', :locals => {:f => f}, model: @movie %>
    <div class="d-flex justify-content-center mt-2">
      <%= f.submit t('create'), class: 'btn btn-outline-dark col-md-2' %>
      <%= link_to t('back'), admin_movies_path, class: 'btn btn-outline-dark col-md-2 ml-2' %>
    </div>
  <% end %>
</div>

app/views/admin/movies/show.html.erb
<%= link_to 'スケジュール', admin_movie_schedules_path(params[:id]), class: 'btn btn-outline-dark' %>

app/views/admin/reservations/_form.html.erb
<%= render "layouts/error_messages" %>
<p class="form-group field">
  <%= f.label :sheet_id, "座席", class: "control-label" %>
  <%= f.text_field :sheet_id, class: "form-control" %>
</p>
<p class="form-group field">
  <%= f.label :date, "日時", class: "control-label" %>
  <%= f.text_field :date, class: "form-control" %>
</p>
<p class="form-group field">
  <%= f.label :name, "名前", class: "control-label" %>
  <%= f.text_field :name, class: "form-control" %>
</p>
<p class="form-group field">
  <%= f.label :email, "メールアドレス", class: "control-label" %>
  <%= f.text_area :email, class: "form-control" %>
</p>

app/views/admin/reservations/edit.html.erb
<div class="container ">
  <%= form_for @reservations, url: admin_reservation_path(@reservations) do |f| %>
    <%= render :partial => 'form', :locals => {:f => f} %>
    <%= f.submit t('update'), class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/admin/reservations/index.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center">
    <h1 >予約一覧</h1>
    <% if flash[:notice] %>
      <div class="alert alert-danger"><%= flash[:notice] %></div>
    <% end %>
    <%= link_to "予約追加", new_admin_reservation_path, class: 'btn btn-primary' %>
  </div>
  <div class="mt-2">
    <table class="table">
      <thead>
        <th>映画作品</th>
        <th>座席</th>
        <th>日時</th>
        <th>名前</th>
        <th>メールアドレス</th>
        <th></th>
        <th></th>
      </thead>
      <tbody>
        <% @reservations.each do |reservation| %>
          <tr class="mt-1">
            <td>
              <% @movies.each do |movie| %>
                <% if movie.id == reservation.movie_id %>
                  <%= movie.name %>
                <% end %>
              <%%>
            </td>
            <td><%= reservation.sheet_id %></td>
            <td><%= reservation.date %></td>
            <td><%= reservation.name %></td>
            <td><%= reservation.email %></td>
            <td><%= link_to '詳細・修正', edit_admin_reservation_path(reservation), class: 'btn btn-outline-dark' %></td>
            <td><%= link_to "削除", admin_reservation_path(reservation.id), class: 'btn btn-outline-danger', method: :delete, data: { confirm: "削除しますか？" } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/schedules/_form.html.erb
 <div class="container mt-4">
  <div class="d-flex align-items-center justify-content-center mt-2">
    <%= f.label :start_time, "開始時刻", class: "col-sm-2 col-form-label" %>
    <div class="col-md-4">
      <%= f.time_field :start_time, class: "form-control" %>
    </div>
  </div>
  <div class="d-flex align-items-center justify-content-center mt-2">
    <%= f.label :end_time, "終了時刻", class: "col-sm-2 col-form-label" %>
    <div class="col-md-4">
      <%= f.time_field :end_time, class: "form-control" %>
    </div>
  </div>
</div>

app/views/admin/schedules/edit.html.erb
<div class="container">
  <%= form_for @schedule, url: admin_schedule_path(@schedule) do |f| %>
    <%= render :partial => 'form', :locals => {:f => f}, model: @schedule %>
    <div class="d-flex justify-content-center mt-2">
      <%= f.submit t('update'), class: 'btn btn-outline-dark col-md-2' %>
      <%= link_to '戻る', admin_movie_schedules_path(params[:id]), class: 'btn btn-outline-dark col-md-2 ml-2' %>
    </div>
  <% end %>
</div>

app/views/admin/schedules/index.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center">
    <h1 >スケジュール一覧</h1>
    <h2><%= @schedule_name %></h2>
    <% if flash[:notice] %>
      <div class="alert alert-danger"><%= flash[:notice] %></div>
    <% end %>
    <div class="d-flex justify-content-center mt-2">
      <%= link_to "管理一覧", admin_movies_path, class: 'btn btn-outline-primary' %>
      <%= link_to "新規登録", new_admin_movie_schedule_path(id: params[:id]), class: 'btn btn-outline-primary ml-2' %>
    </div>
  </div>
  <div>
    <% @schedules.each do |schedule| %>
    <div class="d-flex justify-content-between align-items-center mt-2">
      <div>上映開始時刻: <%= schedule.start_time.to_s(:time_jp) %> / 上映終了時刻: <%= schedule.end_time.to_s(:time_jp) %></div>
      <div>
        <%= link_to '編集', edit_admin_schedule_path(schedule), class: 'btn btn-outline-dark' %>
        <%= link_to "削除", admin_schedule_path(id: schedule.id, movie_id: schedule.movie_id), class: 'btn btn-outline-danger', method: :delete, data: { confirm: "削除しますか？" } %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/schedules/new.html.erb
<div class="container">
  <%= form_for @schedule, url: admin_movie_schedules_path(movie_id: params[:movie_id]) do |f| %>
    <%= render :partial => 'form', :locals => {:f => f}, model: @schedule %>
    <div class="d-flex justify-content-center mt-2">
      <%= f.submit t('create'), class: 'btn btn-outline-dark col-md-2' %>
      <%= link_to t('back'), admin_movie_schedules_path(params[:movie_id]), class: 'btn btn-outline-dark col-md-2 ml-2' %>
    </div>
  <% end %>
</div>

app/views/admin/schedules/show.html.erb
aaaaaa

app/views/layouts/_error_messages.html.erb
<% if flash[:error_messages] %>
  <div class='alert alert-danger'>
    <ul>
      <% flash[:error_messages].each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_message.html.erb
<% if flash[:messages] %>
  <div class='alert alert-primary'>
    <ul>
      <% flash[:messages].each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechtrainRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<div class="container">
  <h1 class="my-3 ml-3">movie</h1>
  <div class="d-flex mb-3">
    <%= form_tag(movies_path, method: :get) do %>
      <div class="input-group">
        <%= text_field_tag :search, params[:search], class: 'form-control' %> 
        <%= submit_tag "検索" ,class: 'btn btn-primary ml-1' %> 
      </div>
      <div class="form-check form-check-inline">
        <%= radio_button_tag :is_showing, "", params[:is_showing].blank? %>
        <%= label_tag nil, 'すべて', class: 'form-check-label ml-1' %>
      </div>
      <div class="form-check form-check-inline">
        <%= radio_button_tag :is_showing, "0", params[:is_showing] == "0" %>
        <%= label_tag nil, '公開予定', class: 'form-check-label ml-1' %>
      </div>
      <div class="form-check form-check-inline">
        <%= radio_button_tag :is_showing, "1", params[:is_showing] == "1" %>
        <%= label_tag nil, '公開中', class: 'form-check-label ml-1' %>
      </div>
    <% end %> 
  </div>
  <div>
    <table class="table">
    <thead>
      <th>タイトル</th>
      <th>上映予定</th>
      <th></th>
    </thead>
    <tbody>
      <% @movies.each do |movie| %>
        <tr class="mt-1">
          <td><%= movie.name %></td>
          <td><%= movie.is_showing ? '上映中' : '上映予定' %></td>
          <td><%= link_to '詳細', movie, class: 'btn btn-outline-dark' %></td>
        </tr>
      <% end %>
    </tbody>
    </table>
  </div>
</div>

app/views/movies/show.html.erb
<div class="container mt-4">
  <%= render "layouts/error_messages", locals: { model: @movie } %> 
  <% if flash[:notice] %>
    <div class="alert alert-success"><%= flash[:notice] %></div>
  <% end %>
  <div class="d-flex align-items-center justify-content-center">
    <label for="title" class="col-sm-2 col-form-label">タイトル</label>
    <div class="col-md-4">
      <input type="text" readonly class="form-control-plaintext h3" id="title" value="<%= @movie.name %>">
    </div>
  </div>
  <div class="d-flex align-items-center justify-content-center">
    <label for="year" class="col-sm-2 col-form-label">公開年</label>
    <div class="col-md-4">
      <input type="text" readonly class="form-control-plaintext h3" id="year" value="<%= @movie.year %>年">
    </div>
  </div>
  <div class="d-flex align-items-center justify-content-center">
    <label for="description" class="col-sm-2 col-form-label">詳細</label>
    <div class="col-md-4">
      <input type="text" readonly class="form-control-plaintext h3" id="description" value="<%= @movie.description == '' ? '記載なし' : @movie.description %>">
    </div>
  </div>
  <div class="d-flex align-items-center justify-content-center">
    <label class="col-sm-2 col-form-label"></label>
    <div class="col-md-4">
      <input type="text" readonly class="form-control-plaintext h3" value="<%= @movie.is_showing ? '上映中' : '上映予定' %>">
    </div>
  </div>
  <% if @schedule.present? %>
    <div class="d-flex align-items-center justify-content-center">
      <label class="col-sm-2 col-form-label">上映時刻</label>
      <div class="col-md-4">
        <ul class="list-group">
          <% @schedule_hash[:start_time].each_with_index do |item,i| %>
            <li class="list-group-item"><%= item.to_s(:time_jp) %>~<%= @schedule_hash[:end_time][i].to_s(:time_jp) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <%= form_with url: movie_setup_resevation_path(movie_id: params[:id]), method: :get, local: true do |f| %>
    <div class="d-flex align-items-center justify-content-center mt-2">
      <%= f.label :date, "日付", class: "col-sm-2 col-form-label" %>
      <div class="col-md-4">
        <%= f.select :date, (Date.today..(Date.today + 6.days)).map {|i| [i.strftime("%Y/%m/%d"), i.strftime("%F")]}, {}, class: 'form-control' %> 
      </div>
    </div>
    <div class="d-flex align-items-center justify-content-center mt-2">
      <%= f.label :start_time, "上映開始時間", class: "col-sm-2 col-form-label" %>
      <div class="col-md-4">
        <%= f.select :start_time, @time_arr, { selected: @time }, { class: 'form-control' } %>
      </div>
    </div>
    <%= f.hidden_field :schedule_id, value: "1" %>
    <div class="d-flex justify-content-center mt-2">
      <%= f.submit '座席を予約する', class: 'btn btn-outline-dark col-md-2' %>
      <%= link_to '戻る', movies_path, class: 'btn btn-outline-dark col-md-2 ml-2' %>
    </div>
  <% end %>
</div>

app/views/reservations/new.html.erb
<div class="container">
  <%= form_with url: movie_schedule_reservations_path(movie_id: params[:movie_id], schedule_id: params[:schedule_id]), local: true do |f| %>
    <div style="text-align: -webkit-center">
    <div class="form-group field">
      <%= f.label :name, "予約者氏名", class: "control-label" %>
      <div class="col-md-4">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div class="form-group field">
      <%= f.label :email, "メールアドレス", class: "control-label" %>
      <div class="col-md-4">
        <%= f.email_field :email, class: "form-control" %>
      </div>
    </div>
    <%= f.hidden_field :date, value: params[:date] %>
    <%= f.hidden_field :sheet_id, value: params[:sheet_id] %>
    <%= f.submit t('create'), class: 'btn btn-primary text-right' %>
    </div>
  <% end %>
</div>

app/views/sheets/index.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center">
    <h1 >座席配置</h1>
    <% if flash[:error] %>
      <div class="alert alert-danger"><%= flash[:error] %></div>
    <% end %>
  </div>
  <div class="mt-2">
    <table class="table table-bordered text-center">
      <thead>
        <th></th>
        <th></th>
        <th>スクリーン</th>
        <th></th>
        <th></th>
      </thead>
      <tbody>
      <% @sheets.each_slice(5) do |sheet| %>
        <tr class="mt-1">
          <% sheet.each do |cl| %>
            <% if @reserved_sheet_ids.include?(cl.id) %>
            <td class='bg-secondary'>
              <%= cl.row %>-<%= cl.column %>
            </td>
            <% else %>
              <td >
                <%= link_to new_movie_schedule_reservation_path(date: params[:start_time], sheet_id: cl.id), tabindex:"-1" do %>
                  <%= cl.row %>-<%= cl.column %>
                <% end %>
              </td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>